name: mobilepay_flutter_stripe
description: A Flutter plugin for integrating MobilePay with Stripe.
version: 0.0.1
homepage: https://github.com/Shahidbangash/mobilepay_flutter_stripe
repository: https://github.com/Shahidbangash/mobilepay_flutter_stripe
issue_tracker: https://github.com/Shahidbangash/mobilepay_flutter_stripe/issues

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.mobilepay_flutter_stripe
        pluginClass: MobilepayFlutterStripePlugin


